In [5]:
import pandas as pd

In [6]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['sia','Ravi','geet','ajeenkya','Avinash'])
marks = pd.Series([85,67,59,40,90])

In [7]:
df = pd.DataFrame({
    'id':roll,
    'name':name,
    'marks':marks
})

In [8]:
df

   id      name  marks
0   1       sia     85
1   2      Ravi     67
2   3      geet     59
3   4  ajeenkya     40
4   5   Avinash     90

In [9]:
df.ndim

2

In [10]:
df.shape

(5, 3)

In [11]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [12]:
pwd

'C:\\Users\\91898'

In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("student.csv")

In [15]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [16]:
df.shape

(10, 5)

In [17]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [18]:
# student1.csv

In [19]:
df = pd.read_csv("student1.csv")

In [20]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [21]:
df.shape

(9, 5)

In [22]:
df.columns

Index(['1', 'anil', 'TE', '56.77', '22'], dtype='object')

In [23]:
col  = ['roll','name','class','marks','age']

In [24]:
df = pd.read_csv('student1.csv',names = col)

In [25]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [26]:
# student3.csv

In [29]:
df = pd.read_csv('student3.tsv', sep = '\t')

In [30]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21